name: Build and Publish SmartSelector.Selenium NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "3.1.x"

      - name: Install PowerShell
        run: sudo apt-get install -y powershell

      - name: Extract Project Version
        id: get_version
        run: |
          $version = [xml](Get-Content SmartSelectors/SmartSelectors.Selenium/SmartSelectors.Selenium.csproj)
          echo "::set-output name=PROJECT_VERSION::$($version.Project.PropertyGroup.Version)"
        shell: pwsh

      - name: Get Published Version
        id: get_published_version
        run: |
          $packageName = "SmartSelectors.Selenium"
          $url = "https://api.nuget.org/v3-flatcontainer/$packageName/index.json"
          $publishedVersion = Invoke-RestMethod -Method Get -Uri $url
          echo "::set-output name=PUBLISHED_VERSION::$( $publishedVersion.versions[-1] )"
        shell: pwsh

      - name: Publish Package if Version Changed
        if: steps.get_version.outputs.PROJECT_VERSION != steps.get_published_version.outputs.PUBLISHED_VERSION
        run: |
          dotnet build --configuration Release --no-restore SmartSelectors/SmartSelectors.Selenium/SmartSelectors.Selenium.csproj
          dotnet pack --configuration Release --no-build --output nupkgs SmartSelectors/SmartSelectors.Selenium/SmartSelectors.Selenium.csproj
          dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
