name: publish-SmartSelectors
on:
  push:
    branches:
      - master # Your default release branch
jobs:
  publish:
    name: publish to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Publish
      - name: publish SmartSelectors on version change
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: SmartSelectors/SmartSelectors/SmartSelectors.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          # TAG_COMMIT: true # Flag to enable / disalge git tagging
          TAG_FORMAT: SmartSelectors.v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_KEY}} # nuget.org API key
